import type { Metadata } from "next";
import { inter } from "../ui/fonts";
import "./globals.css";
import { HamburguerIcon } from "@/ui/icons/hamburguer-icon";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col`}>
        <header className="flex justify-end px-6 pt-6 pb-3  ">
          <HamburguerIcon />
        </header>
        {children}
      </body>
    </html>
  );
}
